### ISSUE TITLE
What is the difference between para-impute and DistributedMissForest ?

### ISSUE THREAD

**Issue by NicolasMICAUX** [fangzhouli/para-impute#1]
There are 2 similar packages on pypi:
https://pypi.org/project/para-impute/
https://pypi.org/project/DistributedMissForest/

The Readme.md files are very similar.

What is the difference between those packages?

**Comment by fangzhouli** [comment]
Hi, I'm sorry for a late response. Please use para-impute! DistributedMissForest is slightly outdated.
